#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

link:
    path:  /link
    controller: App\Controller\LinkController::index
    requirements:
        _methods: GET

link_post:
    path:  /link_post
    controller: App\Controller\LinkController::post
    requirements:
        _methods: POST

blog_list:
        path:      /blog/{page}
        controller: App\Controller\TestController::list
        defaults:
            page: 'fgh'
        requirements:
            page: '\d+'

article_show:
  path:     /articles/{_locale}/{year}/{slug}.{_format}
  controller: App\Controller\ArticleController::show
  defaults:
      _format: html
  requirements:
      _locale:  en|fr
      _format:  html|rss
      year:     \d+