#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

blog_list:
        path:      /blog/{page}
        controller: App\Controller\TestController::list
        defaults:
            page: 'fgh'
      #  requirements:
       #     page: '\d+'